### ISSUE TITLE
No AppleScript option

### ISSUE THREAD

**Issue by schwiet** [getsenic/nuimo-app-osx-actions#14]
In version 1.4.2(12) of the OS X app, I do not have an AppleScript option, as the blog post referenced describes.
<img width="661" alt="screen shot 2016-07-05 at 8 52 15 am" src="https://cloud.githubusercontent.com/assets/5373445/16586953/f62ee056-428d-11e6-86c7-431a3990ee77.png">

**Comment by larsblumberg** [comment]
Hi @schwiet, you're using OS X 10.10 and OS X 10.10 causes a bug when rendering the UI layout of the Nuimo app. We're working on that. If you can however upgrade to OS X 10.11, you'll have a properly shown UI that shows the AppleScript option.

**Comment by schwiet** [comment]
Thanks! I had gone thru this long process of creating an OS X Service and mapping a keyboard shortcut to it, cause I didn't realize that extra dropdown was there. Way better to be able to put the AppleScript straight into the Nuimo app (seems more responsive than Service shortcut was, too) 👍
