### ISSUE TITLE
I want to control iTunes

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/nuimo-app-osx-actions#9]
http://alvinalexander.com/apple/itunes-applescript-examples-scripts-mac-reference

**Comment by stevejalim** [comment]
Related to this, why is iTunes not in the list of available Applications I can spec controls for, please?

**Comment by larsblumberg** [comment]
Hi Steve, feel free to add preset actions for iTunes – just create a folder named `iTunes` and create the actions. Please let me know if you need any help for that – I'm happy to assist.

**Comment by stevejalim** [comment]
@larsblumberg Thanks - I think i must have not looked since updating the OSX app -- I see it in my list of apps, too! Apologies for the distraction

**Comment by larsblumberg** [comment]
Did you already create these actions? They're not yet part of this actions repository.

**Comment by stevejalim** [comment]
No, not created them yet - will share them if/when I have time to set them
up. At the moment am deciding whether to have my Nuimo at home (+ phone +
Sonos) or at the office. I should have backed for two, not one! :o)

**Comment by larsblumberg** [comment]
That's not very difficult – just preorder another one ;)
Looking forward to seeing you sharing your iTunes actions with everybody!

**Comment by ejwill** [comment]
I have created the actions in my current pull request.  Volume control may not be as smooth as people would like; with some feedback I can improve it.

**Comment by larsblumberg** [comment]
@ejwill: We're working on an update that will allow to access the rotation value of Nuimo's wheel. This should allow for a smoother scrolling.

**Comment by ejwill** [comment]
@larsblumberg this issue should be closed now with the merge of my code.

**Comment by larsblumberg** [comment]
You're right, thanks again for your PR.
